# import numpy

In [1]:
import numpy as np

## array 1D

In [2]:
array_1D = np.array([1,2,3])
print(array_1D)

[1 2 3]


In [3]:
for i in array_1D:
    print(i)

1
2
3


## array 2D

In [4]:
array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


### navigation array 2D

In [5]:
for i in array_2D:
    for j in i:
        print(j)

1
2
3
4
5
6


### array 3D

In [6]:
e = np.array([[[ 1,  2,  3],[ 4,  5,  6]],[[ 7,  8,  9],[10, 11, 12]]])
print(e)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### navigation array 3D

In [7]:
for i in e:
    for j in i:
        for z in j:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
