# import numpy

In [1]:
import numpy as np

## Function

### nditer()

In [2]:
array_3D = np.array([[[ 1,  2,  3],[ 4,  5,  6]],[[ 7,  8,  9],[10, 11, 12]]])

In [3]:
for i in np.nditer(array_3D):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


#### op_dtypes

In [4]:
array1 = np.array([1,2,3])

In [5]:
for i in np.nditer(array1, flags=['buffered'] , op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'


#### navigation array with slice

In [6]:
array2 = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
for i in np.nditer(array2[:,::2]):
    print(i)

1
3
5
7


#### ndenumerate()

##### navigation array with index

In [8]:
array3 = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
for idx, j in np.ndenumerate(array3):
    print(idx,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


#### change elements in array

In [10]:
array_1D = np.array([2,6,8])
print(array_1D)

[2 6 8]


In [11]:
array_1D[[1,2]] = 9,10
print(array_1D)

[ 2  9 10]


In [12]:
array_2D = np.array([[1,2,3],[4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [13]:
array_2D[1][1] = 6
print(array_2D)

[[1 2 3]
 [4 6 6]]
