# import numpy

In [1]:
import numpy as np

### slice

In [2]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

#### Column extraction

In [3]:
print(array1.reshape(3,3))
print('************')
print(array1[...,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
************
[2 5 8]


In [4]:
print(array1.reshape(3,3))
print('************')
print(array1[...,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
************
[3 6 9]


#### Row extraction

In [5]:
print(array1.reshape(3,3))
print('************')
print(array1[1,...])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
************
[4 5 6]


In [6]:
print(array1.reshape(3,3))
print('************')
print(array1[2,...])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
************
[7 8 9]
