# import numpy

In [1]:
import numpy as np

### operation +

In [2]:
array1 = np.array([[2,4,6],[8,10,12]])
array2 = np.array([[1,3,5],[7,9,11]])

In [3]:
print(f'befor:\n {array1}')
print('***********')
print(f'ater:\n {array1+2}')

befor:
 [[ 2  4  6]
 [ 8 10 12]]
***********
ater:
 [[ 4  6  8]
 [10 12 14]]


In [4]:
print(array1+array2)

[[ 3  7 11]
 [15 19 23]]


### operation -

In [5]:
print(array2-array1)

[[-1 -1 -1]
 [-1 -1 -1]]


### operation *

In [6]:
print(array1*3)

[[ 6 12 18]
 [24 30 36]]


### operation /

In [7]:
print(array1/2)

[[1. 2. 3.]
 [4. 5. 6.]]


### operation **

In [8]:
print(array1**3)

[[   8   64  216]
 [ 512 1000 1728]]


### operation //

In [9]:
print(array1//2)

[[1 2 3]
 [4 5 6]]


### operation (> , == , !=)

In [10]:
print(array1 > 6)
print('************')
print(array1==6)
print('************')
print(array1>array2)
print('************')
print(array1 != 8)
print('************')

[[False False False]
 [ True  True  True]]
************
[[False False  True]
 [False False False]]
************
[[ True  True  True]
 [ True  True  True]]
************
[[ True  True  True]
 [False  True  True]]
************
