# import numpy

In [1]:
import numpy as np

### rand()

##### np.random.rand(row , column)

In [2]:
array1 = np.random.rand(3,3)
print(array1)

[[0.81043224 0.39845187 0.89162507]
 [0.27035815 0.30224363 0.14476758]
 [0.34327837 0.24597189 0.8085894 ]]


In [3]:
array2 = np.random.rand(3,4)
print(array2)

[[0.92876327 0.97543907 0.91399415 0.53688581]
 [0.26974706 0.08733163 0.99008041 0.00179723]
 [0.92691238 0.66639223 0.23064602 0.47000866]]


In [4]:
array3 = np.random.rand(2)
print(array3)

[0.22970511 0.57330153]


##### Replace columns and rows in array with T

In [5]:
array4 = np.array([[2,4,6],[8,10,12]])
print(f'befor:\n {array4}')
print('***********')
print(f'after:\n {array4.T}')

befor:
 [[ 2  4  6]
 [ 8 10 12]]
***********
after:
 [[ 2  8]
 [ 4 10]
 [ 6 12]]
