# import numpy

In [1]:
import numpy as np

### reshape

In [2]:
array1 = np.array([[1,2,3],[4,5,6]])

In [3]:
print(array1)

[[1 2 3]
 [4 5 6]]


In [4]:
print(array1.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


##### create column array

In [5]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2.reshape(-1,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


##### create row array

In [6]:
array3 = np.array([[1,2,3],[4,5,6]])
print(array3.reshape(1,-1))

[[1 2 3 4 5 6]]
