# import numpy

In [1]:
import numpy as np

### flatten

In [2]:
array1 = np.array([[1,2,3],[4,5,6]])

In [3]:
print(array1)
print('*********')
print(array1.flatten())

[[1 2 3]
 [4 5 6]]
*********
[1 2 3 4 5 6]


In [4]:
array2 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [5]:
print(array2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
