# impoer numpy

In [1]:
import numpy as np

### size

In [2]:
array1 = np.array([[1,2,3],[4,5,6]])

In [3]:
array2 = np.array([[[ 1,  2,  3],[ 4,  5,  6]],[[ 7,  8,  9],[10, 11, 12]]])

In [4]:
print(array1.size)
print('*********')
print(array2.size)

6
*********
12


#### resize

In [5]:
array3 = np.array([[1,2,3],[4,5,6]])

In [6]:
print(array3)
print('*********')
array3.resize(3,2)
print(array3)

[[1 2 3]
 [4 5 6]]
*********
[[1 2]
 [3 4]
 [5 6]]


#### itemsize (In bytes)

In [7]:
array4 = np.array([[1,2,3],[4,5,6]])

In [8]:
print(f'size in byte: {array4.itemsize}')

size in byte: 4
