# import numpy

In [1]:
import numpy as np

#### ones()

##### np.ones((row,column))

In [2]:
array1 = np.ones((3,4) , dtype=int)
print(array1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### zeros()

##### np.zeros((row,column))

In [3]:
array2 = np.zeros((3,4) , dtype=int)
print(array2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
