# import numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1,6,4],[3,5,9]])

In [3]:
print(f'befor sorting:\n {array1}')
array1.sort()
print(f'after sorting:\n {array1}')

befor sorting:
 [[1 6 4]
 [3 5 9]]
after sorting:
 [[1 4 6]
 [3 5 9]]


In [4]:
array2 = np.random.rand(3,3)

In [5]:
print(f'befor sorting:\n {array2}')
array2.sort()
print(f'after sorting:\n {array2}')

befor sorting:
 [[0.55811579 0.08058337 0.29546421]
 [0.70244064 0.53570462 0.76913877]
 [0.15857514 0.03088794 0.62861744]]
after sorting:
 [[0.08058337 0.29546421 0.55811579]
 [0.53570462 0.70244064 0.76913877]
 [0.03088794 0.15857514 0.62861744]]
