# import numpy

In [1]:
import numpy as np

#### tile()

In [2]:
array1 = np.tile(6,3)

In [3]:
print(array1)

[6 6 6]


In [4]:
array2 = np.tile(3,6)

In [5]:
print(array2)

[3 3 3 3 3 3]


In [6]:
array3 = np.array([[1,2,3],[4,5,6]])

In [7]:
array4 = np.tile(array3,2)

In [8]:
print(array3)
print('*'*20)
print(array4)

[[1 2 3]
 [4 5 6]]
********************
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
