# import numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1,2],
                   [3,4]])

array2 = np.array([[5,6],
                   [7,8]])

array3 = [5,6]

#### vertical stacking

In [3]:
print('vertical stacking:\n', np.vstack((array1,array2)))

vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### horizontal stacking

In [4]:
print('horizontal stacking:\n' , np.hstack((array1,array2)))

horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


#### column stacking

In [5]:
print('column stacking:\n' , np.column_stack((array1,array3)))

column stacking:
 [[1 2 5]
 [3 4 6]]


#### concatenating

In [6]:
print('concatenating to 2nd axis:\n' , np.concatenate((array1,array2),1))

concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]
