# import numpy

In [1]:
import numpy as np

#### rand()

In [2]:
array1 = np.random.rand()
array2 = np.random.rand(2,2)

In [3]:
print(array1)
print('*'*20)
print(array2)

0.7038230693120092
********************
[[0.08986675 0.54003554]
 [0.30110814 0.33304006]]


#### randn()

In [4]:
N = 5
a= 5.
b = 2.
var = b ** 2

In [5]:
array3 = a + var * np.random.randn(N,3)

In [6]:
print(array3)

[[ 6.025091    2.76505836  8.40192305]
 [ 4.58445298 -1.28645853 12.1705026 ]
 [14.70221619  4.82210773  2.57996176]
 [ 1.6314453  -1.8579356   8.72978301]
 [ 4.34953822  3.46188087  5.56949958]]


#### randint()

In [7]:
array4 = np.random.randint(low = 4 , high = 10 , size = 5)

In [8]:
print(array4)

[6 7 4 6 9]


#### shuffle()

In [9]:
letters = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

In [10]:
print(letters)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [11]:
np.random.shuffle(letters)
print(letters)

['d', 'p', 'n', 'v', 'a', 'k', 't', 'j', 'i', 'f', 'o', 'e', 'w', 'u', 'z', 'l', 'c', 'y', 'b', 'g', 'h', 'm', 'x', 'q', 's', 'r']


#### permutation()

In [12]:
letters2 = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

In [13]:
print(np.random.permutation(letters2))

['a' 'c' 'i' 'e' 'j' 'n' 'f' 'q' 'g' 'w' 'l' 'p' 'u' 'h' 'm' 'b' 'v' 'k'
 't' 'r' 'y' 'o' 'd' 's' 'z' 'x']


In [14]:
print(np.random.permutation(10))

[2 5 6 0 7 3 8 9 1 4]


#### choice()

In [15]:
letters3 = ['a','b','c','d']

In [16]:
for _ in range(5):
    selection = np.random.choice(letters3)
    print(selection)

c
a
c
c
d


#### sample()

In [17]:
from random import sample

In [18]:
letters4 = ['a','b','c','d']

In [19]:
subset = sample(letters4 , 3)

In [20]:
print(subset)

['a', 'c', 'd']
